[workspace]
members = [
	"crates/popsub",
	"crates/popsub_broker",
	"crates/popsub_client",
	"crates/popsub_config",
	"crates/popsub_persistence",
	"crates/popsub_transport",
	"crates/popsub_utils",
]
resolver = "3"
