[package]
name = "popsub_client"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.8", features = ["v4"] }
tokio = { version = "1.46.1", features = ["full"] }
tungstenite = "0.28.0"
